import { Article, type ArticleAttributes } from "./article";

export const templateGetAllArticles: ArticleAttributes[] = [
  {
    id: "1",
    title: "Artigo sobre IA",
    user: {
      user_id: "1",
      name: "Autor Principal",
      urlPerfil: "https://example.com/autor1.png",
    },
    colaborators_id: [
      {
        name: "Leonardo",
        user_id: "4",
        urlPerfil: "https://example.com/leonardo.png",
      },
    ],
    event: {
      evento_id: 1,
      img_url_evento: "https://example.com/evento1.png",
      title: "Evento de Tecnologia",
      description: "Evento sobre inovações em tecnologia",
      dt_start: "2025-01-10T08:00:00Z",
      dt_end: "2025-01-12T18:00:00Z",
      status: "ativo",
      created_at: "2024-12-01T12:00:00Z",
      updated_at: "2024-12-10T12:00:00Z",
    },
    key_words: ["IA", "Desenvolvimento em Desktop"],
    likes: 4,
    resume: "Um resumo legal",
    status: "created",
    tematic_area: ["IA"],
    url: "path://algo.com",
    version: 1,
    created_at: "2025-05-01T10:00:00Z",
    updated_at: "2025-05-01T10:00:00Z",
  },
  {
    id: "2",
    title: "Prototipação com Arduino",
    user: {
      user_id: "1",
      name: "Autor Principal",
      urlPerfil: "https://example.com/autor1.png",
    },
    colaborators_id: [],
    event: {
      evento_id: 1,
      img_url_evento: "https://example.com/evento1.png",
      title: "Evento de Tecnologia",
      description: "Evento sobre inovações em tecnologia",
      dt_start: "2025-01-10T08:00:00Z",
      dt_end: "2025-01-12T18:00:00Z",
      status: "ativo",
      created_at: "2024-12-01T12:00:00Z",
      updated_at: "2024-12-10T12:00:00Z",
    },
    key_words: ["Ciência e tecnologia", "Arduino"],
    likes: 4,
    resume: "Projeto de prototipação",
    status: "created",
    tematic_area: ["IA"],
    url: "path://algo.com",
    version: 1,
    created_at: "2025-05-01T10:00:00Z",
    updated_at: "2025-05-01T10:00:00Z",
  },
  {
    id: "3",
    title: "Outro Artigo sobre IA",
    user: {
      user_id: "1",
      name: "Autor Principal",
      urlPerfil: "https://example.com/autor1.png",
    },
    colaborators_id: [
      {
        name: "Josue",
        user_id: "10",
        urlPerfil: "https://example.com/josue.png",
      },
    ],
    event: {
      evento_id: 2,
      img_url_evento: "https://example.com/evento2.png",
      title: "Simpósio de Inovação",
      description: "Discussões sobre inteligência artificial e robótica",
      dt_start: "2025-02-15T09:00:00Z",
      dt_end: "2025-02-17T17:00:00Z",
      status: "ativo",
      created_at: "2025-01-05T10:00:00Z",
      updated_at: "2025-01-15T14:00:00Z",
    },
    key_words: ["IA", "Desenvolvimento em Desktop"],
    likes: 4,
    resume: "Um resumo legal",
    status: "created",
    tematic_area: ["IA"],
    url: "path://algo.com",
    version: 1,
    created_at: "2025-05-01T10:00:00Z",
    updated_at: "2025-05-01T10:00:00Z",
  },
];

export const templateGetByIdArticles = new Article({
  id: "1",
  title: "Artigo sobre IA",
  user: {
    user_id: "1",
    name: "Autor Principal",
    urlPerfil: "https://example.com/autor1.png",
  },
  colaborators_id: [
    {
      name: "Leonardo",
      user_id: "4",
      urlPerfil: "https://example.com/leonardo.png",
    },
  ],
  event: {
    evento_id: 1,
    img_url_evento: "https://example.com/evento1.png",
    title: "Evento de Tecnologia",
    description: "Evento sobre inovações em tecnologia",
    dt_start: "2025-01-10T08:00:00Z",
    dt_end: "2025-01-12T18:00:00Z",
    status: "ativo",
    created_at: "2024-12-01T12:00:00Z",
    updated_at: "2024-12-10T12:00:00Z",
  },
  key_words: ["IA", "Desenvolvimento em Desktop"],
  likes: 4,
  resume: "Um resumo legal",
  status: "created",
  tematic_area: ["IA"],
  url: "path://algo.com",
  version: 1,
  created_at: "2025-05-01T10:00:00Z",
  updated_at: "2025-05-01T10:00:00Z",
});
